version: 2
jobs:
  build:
    working_directory: ~/guilhermedeoliveira/projects/training
    docker:
      - image: circleci/node:8
      steps:
        - checkout
        - run: yarn install
        - run: yarn test
